category_banners:
  type: objects
  default: []
  schema:
    name: banner
    properties:
      group:
        type: categories
      image_url:
        type: string
      url:
        type: string
      use_overlay: 
        type: boolean
      overlay_text:
        type: string
      overlay_button_text:
        type: string
      banner_replaces_subcategory:
        type: bool
        description: "Banner replaces a subcategory if this option is checked."
      subcategory_to_replace: 
        type: categories
        description: "Sub category that the benner replaces."
  description: "This text will be displayed under this setting and it explains what the setting does!"

all_resources_access:
  type: objects
  default: []
  schema:
    name: resources_button
    properties:
      category:
        type: categories
      resources_url: 
        type: string
      button_text:
        type: string

      