category_banners:
  type: objects
  default: []
  schema:
    name: banner
    identifier: group
    properties:
      group:
        type: categories
        required: true
        validations: 
          max: 1
      image_url:
        type: string
        required: true
        validations:
          url: true
      url:
        type: string
        validators:
          url: true
      use_overlay: 
        type: boolean
      overlay_text:
        type: string
      overlay_button_text:
        type: string
      decorative_banner_location: 
        type: enum
       
        choices:
          - "ac"
          - "bc"
        
      banner_replaces_subcategory:
        type: boolean
      subcategory_to_replace: 
        type: categories
        validations: 
          max: 1


all_resources_access:
  type: objects
  default: []
  schema:
    name: resources_button
    identifier: category
    properties:
      category:
        type: categories
        required: true
        validations:
          max: 1
      resources_url: 
        type: string
        validations:
          url: true
        required: true
      button_text:
        type: string
        validations:
          min: 4
        required: true

      