category_banners:
  type: objects
  default: []
  schema:
    name: banner
    properties:
      group:
        type: categories
      image_url:
        type: string
      url:
        type: string
  description: "This text will be displayed under this setting and it explains what the setting does!"