category_banners:
  type: objects
  default: []
  schema:
    name: banner
    identifier: group
    properties:
      group:
        type: categories
      image_url:
        type: string
      url:
        type: string
      use_overlay: 
        type: boolean
      overlay_text:
        type: string
      overlay_button_text:
        type: string
      banner_replaces_subcategory:
        type: boolean
      subcategory_to_replace: 
        type: categories


all_resources_access:
  type: objects
  default: []
  schema:
    name: resources_button
    properties:
      category:
        type: categories
      resources_url: 
        type: string
      button_text:
        type: string

      